openapi: 3.0.3
info:
  title: API de tu proyecto
  version: 1.0.0
  description: Documentación OpenAPI generada automáticamente.
paths:
  /api/media/:
    get:
      operationId: media_retrieve
      description: |-
        GET → List media content object
        POST → Create new media content object
      tags:
      - media
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: media_create
      description: |-
        GET → List media content object
        POST → Create new media content object
      tags:
      - media
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/media/{id}/:
    get:
      operationId: media_retrieve_2
      description: |-
        GET → Get one specific media content object
        PUT → Update one media content object
        DELETE → Delete one media content object
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - media
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: media_update
      description: |-
        GET → Get one specific media content object
        PUT → Update one media content object
        DELETE → Delete one media content object
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - media
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: media_destroy
      description: |-
        GET → Get one specific media content object
        PUT → Update one media content object
        DELETE → Delete one media content object
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - media
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/profiles/:
    get:
      operationId: profiles_retrieve
      description: GET → List all users profiles
      tags:
      - profiles
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/profiles/{id}/:
    get:
      operationId: profiles_retrieve_2
      description: |-
        GET → Get one profile
        PUT → Update one profile
        DELETE → Delete one profile
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - profiles
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: profiles_update
      description: |-
        GET → Get one profile
        PUT → Update one profile
        DELETE → Delete one profile
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - profiles
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: profiles_destroy
      description: |-
        GET → Get one profile
        PUT → Update one profile
        DELETE → Delete one profile
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - profiles
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/ratings/:
    get:
      operationId: ratings_retrieve
      description: |-
        GET → List of all ratings
        POST → Create a new rating
      tags:
      - ratings
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: ratings_create
      description: |-
        GET → List of all ratings
        POST → Create a new rating
      tags:
      - ratings
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/ratings/{id}/:
    get:
      operationId: ratings_retrieve_2
      description: |-
        GET → Get one Rating
        PUT → Update one Rating
        DELETE → Delete one Rating
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - ratings
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: ratings_update
      description: |-
        GET → Get one Rating
        PUT → Update one Rating
        DELETE → Delete one Rating
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - ratings
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: ratings_destroy
      description: |-
        GET → Get one Rating
        PUT → Update one Rating
        DELETE → Delete one Rating
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - ratings
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/register/:
    post:
      operationId: register_create
      tags:
      - register
      security:
      - cookieAuth: []
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/test/:
    get:
      operationId: test_retrieve
      tags:
      - test
      security:
      - cookieAuth: []
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/test_autentication/:
    get:
      operationId: test_autentication_retrieve
      tags:
      - test_autentication
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/token/:
    post:
      operationId: token_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /api/token/refresh/:
    post:
      operationId: token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
components:
  schemas:
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - password
      - refresh
      - username
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
      required:
      - access
      - refresh
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
